import 'package:flutter/material.dart';
import 'app_category.dart';

/// Personalized digital wellbeing recommendation generated by AI based on behavioral patterns
class WellbeingRecommendation {
  final String id;
  final String title;
  final String description;
  final String suggestedGoal;
  final AppCategory targetCategory;
  final String impactLevel; // "HIGH", "MEDIUM", "LOW"
  final IconData icon;

  const WellbeingRecommendation({
    required this.id,
    required this.title,
    required this.description,
    required this.suggestedGoal,
    required this.targetCategory,
    this.impactLevel = 'MEDIUM',
    this.icon = Icons.lightbulb_outline_rounded,
  });

  factory WellbeingRecommendation.fromJson(Map<String, dynamic> json) {
    return WellbeingRecommendation(
      id: json['id'] as String? ?? UniqueKey().toString(),
      title: json['title'] as String? ?? 'Personalized Suggestion',
      description: json['description'] as String? ?? '',
      suggestedGoal: json['suggestedGoal'] as String? ?? '',
      targetCategory: AppCategory.fromJson(json['targetCategory'] as String?),
      impactLevel: json['impactLevel'] as String? ?? 'MEDIUM',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'suggestedGoal': suggestedGoal,
      'targetCategory': targetCategory.name,
      'impactLevel': impactLevel,
    };
  }
}
